name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v4



      - name: Set up JDK 22
        uses: actions/setup-java@v1



        with:
          java-version: '22'



      - name: Build with Maven
        run: mvn clean install



      



      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        run: echo "Deploy deploy deploy ..."
